### ISSUE TITLE
Modal para Copa

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/mundialfutebolderua-theme#1]
Matheus, nesse modal da home do site http://www.mundialfutebolderua.org/ precisamos alterar para ele funcionar da seguinte forma:

Ter dois botões:

[ Acompanhe a Copa América ]
no primeiro um link para a Copa América que acabamos de publicar;

[ Conheça o projeto a partir de 2014 ]
e o segundo link deve fechar o modal para pessoa cair no site do Mundial mesmo.

Esse é o modal hoje:
![_copa](https://cloud.githubusercontent.com/assets/1918474/7723503/7901273c-febf-11e4-86b9-b527f6f45da4.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit e já enviado pra producao
